package com.dynatrace.oneagent.sdk.api;

/**
 * Common interface to allow outgoing requests to be linked to incoming requests via tags.
 */
public interface OutgoingTaggable {

	/**
	 * Creates a Dynatrace tag for an outgoing request and returns the string representation of it.
	 * A tag can only be retrieved after the tracer was started (see {@link Tracer#start()}).
	 * 
	 * To allow tracing across process and technology boundaries, tracers can be supplied with so-called tags.
	 * Tags are strings or byte arrays generated by the SDK that enable Dynatrace to trace a transaction end-to-end.
	 * The user has to take care of transporting the tag from one process/service to the other.
	 * 
	 * @return the tag to be used with {@link IncomingTaggable#setDynatraceStringTag(String)}.
	 */
	String getDynatraceStringTag();

	/**
	 * same as {@link #getDynatraceStringTag()} but returning the tag in binary format.
	 * A tag can only be retrieved after the tracer was started (see {@link Tracer#start()}).
	 * 
	 * @return the tag to be used with {@link IncomingTaggable#setDynatraceByteTag(byte[])}.
	 */
	byte[] getDynatraceByteTag();

}